version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - chromadb
    networks:
      - app-network

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./db:/app/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
